name: Deploy Jekyll

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: github-style  # 如果使用主题子模块

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # 匹配你的Gemfile

      - name: Verify directory structure
        run: |
          echo "当前目录内容:"
          ls -la
          echo "docs目录是否存在:"
          ls -ld docs || echo "No docs directory"  # 调试输出

      - name: Build site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./   # 根据实际结构调整 👈 关键参数
          destination: ./_site
          verbose: true  # 启用详细日志

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./_site