name: Hugo Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true  # 如果需要扩展功能

      - name: Build
        run: |
          hugo --minify --cleanDestinationDir
          touch public/.nojekyll  # 关键禁用步骤

      - name: Verify Build Output
        run: ls -la public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: leoandroid/leo.github.io
          publish_branch: master
          publish_dir: ./public
          full_commit_message: |
            Deploy from ${{ github.sha }}
            ${{ github.event.head_commit.message }}